export const GET_ALL_DATA = "GET_ALL_DATA"
export const GET_CAMP_DATA_LOADING = "GET_CAMP_DATA_LOADING"
export const GET_CAMP_DATA_RECEIVED = "GET_CAMP_DATA_RECEIVED"
export const GET_CAMP_DATA_ERROR = "GET_CAMP_DATA_ERROR"

export const GET_SEARCH_DATA="GET_SEARCH_DATA"